### ISSUE TITLE
line>lines

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/gradient-descent-step-sizes-lab#2]
line here

from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)
from graph import plot, trace_values

initial_m_values = list(range(1, 18, 1))
scaled_m_values = list(map(lambda initial_m_value: initial_m_value/10,initial_m_values))
cost_values = rss_values(budgets, revenues, scaled_m_values, 133.33)

if cost_values:
    rss_trace = trace_values(cost_values['m_values'], cost_values['rss_values'], mode = 'line')
    plot([rss_trace])

**Comment by LoreDirick** [comment]
is fixed now!
