### ISSUE TITLE
following along, different returns

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/gradient-descent-step-sizes-lab#3]
what you say:
So the slope_at function takes in our dataset, and returns the slope of the cost curve at that point. So the numbers -296312 and 123877 reflect the slopes at the cost curve when m is .6 and 1.6 respectively.

what i get:
slope_at(budgets, revenues, .6, 133.33333333333326)
{'m': 0.6, 'slope': -296312.3333330441}
slope_at(budgets, revenues, 1.6, 133.33333333333326)
{'m': 1.6, 'slope': 123687.66666691954}

-296312 ~ -296312.3333330441
but
123877 != 123687.66666691954

this could be a "me" problem but i did copy and paste the code in and had everything correct up til this point so thought i'd let you know in case its just a typo or something.

**Comment by mas16** [comment]
Hi annieeby, thanks for the note! The lab has been corrected.
