### ISSUE TITLE
number consistency

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/gradient-descent-step-sizes-lab#4]
"When the curve is steeper and downwards at  m=6"

I think you mean .6

"And at  m=1.3"

think you want to 1.6 (looking above) 

I'd fork and fix but also graph doesn't match numbers in text so I think this part just needs to be redone completely.

**Comment by mas16** [comment]
Hi annieeby, thanks for the note! We have implemented the corrections.
