### ISSUE TITLE
There's a problem with a lot of the ploty functions

### ISSUE THREAD

**Issue by fastaro** [learn-co-curriculum/gradient-descent-step-sizes-lab#8]
I keep getting errors with the prewritten ploty functions.. They all say this - "Invalid value of type 'builtins.str' received for the 'mode' property of scatter
        Received value: 'line'

    The 'mode' property is a flaglist and may be specified
    as a string containing:
      - Any combination of ['lines', 'markers', 'text'] joined with '+' characters
        (e.g. 'lines+markers')
        OR exactly one of ['none'] (e.g. 'none')"

and from what I'm reading, other people have ran into similar issues. I am just curious about how big of an issue is this?   Is it fixable?  all my functions output exactly what is commented so I know it's something to do with ploty.  From what I read online - this issue came up after ploty updated to the 3.0

**Comment by mcarlisle** [comment]
bump - easy fix (just change 'mode' = 'line' to 'lines')
but it appears on several pages

**Comment by LoreDirick** [comment]
should be fixed now!
