### ISSUE TITLE
Graph.py plotting methods all have issues with mode

### ISSUE THREAD

**Issue by harishvkumar** [learn-co-curriculum/gradient-descent-step-sizes-lab#9]
Hi,

the methods in graph.py file all have issues with the modes used to trace a plotly line, can someone please fix this ASAP? its been more than 3 months and this hasnt been addressed at all. Hope this is not the sample of what to expect with the actual course.

**Comment by mcarlisle** [comment]
bump

**Comment by LoreDirick** [comment]
should be fixed now!
